export * from './About';
export * from './Concents';
export * from './Contact/components';
export * from './Contact';
export * from './Home/components';
export * from './Home';
export { default as Login } from './Login';
export { default as PageNotFound } from './PageNotFound';
export { default as RecPassword } from './RecPassword';
export * from './System';
export * from './Tournaments/components';
export * from './Tournaments';
