export { default as Login } from './Login';
export { default as PageNotFound } from './PageNotFound';
export { default as Campeonatos } from './Privado/Campeonatos';
export { default as Codificadores } from './Privado/Codificadores';
export { default as ConsentimientosAdmin } from './Privado/ConsentimientosAdmin';
export { default as Equipos } from './Privado/Equipos';
export { default as Facturas } from './Privado/Facturas';
export { default as Inscripciones } from './Privado/Inscripciones';
export { default as Jugadores } from './Privado/Jugadores';
export { default as ListaNegra } from './Privado/ListaNegra';
export { default as MenuTorneos } from './Privado/MenuTorneos';
export { default as Proveedores } from './Privado/Proveedores';
export { default as Resultados } from './Privado/Resultados';
export { default as Sanciones } from './Privado/Sanciones';
export { default as Sedes } from './Privado/Sedes';
export { default as System } from './Privado/System';
export { default as Torneos } from './Privado/Torneos';
export { default as Usuarios } from './Privado/Usuarios';
export * from './Public/About';
export * from './Public/Concents';
export * from './Public/Contact/components';
export * from './Public/Contact';
export * from './Public/Home/components';
export * from './Public/Home';
export { default as ModalFichaPartido } from './Public/Tournaments/components/ModalFichaPartido';
export { default as Sanctions } from './Public/Tournaments/components/Sanctions';
export { default as TableCards } from './Public/Tournaments/components/TableCards';
export { default as TableMatches } from './Public/Tournaments/components/TableMatches';
export { default as TablePosition } from './Public/Tournaments/components/TablePosition';
export { default as TableScorers } from './Public/Tournaments/components/TableScorers';
export * from './Public/Tournaments';
export * from './Public';
export { default as RecPassword } from './RecPassword';
