export * from './About';
export * from './Concents';
export * from './Contact/components';
export * from './Contact';
export * from './Home/components';
export * from './Home';
export * from './System';
export * from './Tournaments/components';
export * from './Tournaments';
