export * from "./About";
export { default as CentroEntrenamiento } from "./CentroEntrenamiento";
export * from "./Concents";
export * from "./Contact/components";
export * from "./Contact";
export { default as FutbolNP } from "./FutbolNP";
export * from "./Home/components";
export * from "./Home";
export { default as NuevoParadigma } from "./NuevoParadigma";
export { default as ModalFichaPartido } from "./Tournaments/components/ModalFichaPartido";
export { default as Sanctions } from "./Tournaments/components/Sanctions";
export { default as TableCards } from "./Tournaments/components/TableCards";
export { default as TableMatches } from "./Tournaments/components/TableMatches";
export { default as TablePosition } from "./Tournaments/components/TablePosition";
export { default as TableScorers } from "./Tournaments/components/TableScorers";
export * from "./Tournaments";
